### ISSUE TITLE
Wrong Image Size

### ISSUE THREAD

**Issue by rahul059** [mmahrous/thumbler#2]
image is generating of wrong size.

This is how i am using thumbler :-
Thumbler({
                    type: 'image', 
                    input: app.get('baseUrl')+'/public/profile/profile_image-1.jpg',
                    output: app.get('baseUrl')+'/public/thumb/image'+count+'_output.jpeg',                     
                    size: '200x200' // this optional if null will use the desimention of the video 
                }, function(err, path){
                    if (err){
                        return err;
                        console.log("image error");
                    } 
                    console.log("image");
                    return path;
                });

But it is generating wrong size of image

**Comment by rahul059** [comment]
How can we upload image in s3 bucket?

**Comment by rahul059** [comment]
image thumbnail is not working when i don't provide size attribute.
Here is my code

Thumbler({
                    type: 'image', 
                    input: app.get('baseUrl')+'/public/profile/profile_image-3.png',
                    output: app.get('baseUrl')+'/public/thumb/image'+count+'_output.png'                     
                    //size: '200x200' // this optional if null will use the desimention of the video 
                }, function(err, path){
                    if (err){
                        return err;
                        console.log("image error");
                    } 
                    console.log("image");
                    return path;
                });

**Comment by rahul059** [comment]
How can we maintain aspect ratio of image?

**Comment by mmahrous** [comment]
I'm gonna close this for now if you still have the issue please reopen.
